api-addr: :8088

# debug, info, warn, error
logs:
  level: debug
  #format: json
  #filename: logs/go-iot.log

# es config
es:
  url: http://localhost:9200
  usename: 
  password: 
  numberOfShards: 1
  numberOfReplicas: 0
# redis config
redis:
  addr: localhost:6379
  db: 0
  password: 

# 集群配置
cluster:
  enabled: false
  name: 
  index: 1
  token: abc
  # url: http://192.168.31.221:8080
  # hosts: http://192.168.31.221:8080,http://192.168.31.136:8080